### PR TITLE
Sync optimization

### LINKED ISSUE #22: Get rid of unnecessary (de)registration requests during scheduled sync
We should rewrite the sync job so we could get rid of some unnecessary request to Consul. This should  improve our metrics btw.
What is more, the stored Consul-agents list could be generated from existing Consul services (not Marathon apps) and cleaned up when needed.

### PR DESCRIPTION
**Pull request by dankraw**
fixes #22

### CODE REVIEW

**Comment by janisz** [comment]
Can you add test case for:

> What is more, the stored Consul-agents list could be generated from existing Consul services (not Marathon apps) and cleaned up when needed.

**Comment by dankraw** [comment]
Well, actually it's not implemented. The assumption was wrong btw, as we cannot get agents from Consul as we don't know how access the first Consul agent. :) During sync I just prefetch agent nodes locations from application instances that are appropriately labeled. As we talked already the agents list is not cleared, as that's not an issue right now.

The main point of the issue is implemented: there are less requests to Consul during sync and logs should be more accurate.

**Comment by janisz** [comment]
:+1:

**Comment by dankraw** [comment]
Basically, this is the improved part:

```go
for _, task := range app.Tasks {
	if _, ok := consulServicesIdsSet[task.ID]; !ok {
		// [...]
		err := s.service.Register(service)
		// [...]
	} else {
		log.WithField("Id", task.ID).Debug("Task already registered in Consul")
	}
}
```

plus getting the agents - so sync at anytime should be successful (without waiting for Marathon events):

```go
s.addAgentNodes(apps)
```

**Comment by janisz** [comment]
Now everything is clear. Read to merge

**Pull request merged**
